### ISSUE TITLE
Great Library

### ISSUE THREAD

**Issue by linlak** [saulchelewani/ussd-adapter#2]
I found this library great for my use case however it is not compatible with most USSD providers.
I have developed a simple node js express where i route ussd call and format the data to fit in with the request object required.
I will share the code link if you need to try it

**Comment by saulchelewani** [comment]
Hi Linus,

Please share I would love to see that.

This package was developed for Truroute USSD GW. So I guess that's why it
didn't work for your use case. Most telcos have different interfaces so
they require different implementation.

Let's have a look at your case and see if we can create a folk or an
extension to match.

Regards

**Comment by linlak** [comment]
https://github.com/linlak/ussd

**Comment by linlak** [comment]
> https://github.com/linlak/ussd

still working on the read me file

**Comment by saulchelewani** [comment]
@linlak the package now has interfaces you can use for implementation with other USSD providers. 

[Extending for Multiple Implementations](https://github.com/saulchelewani/ussd-adapter#extending-for-multiple-implemtentation)
